### PR TITLE
Mroonga(Groonga)連携

### PR DESCRIPTION
**Pull request by WhiteRaven777**
MySQLで高速な全文検索が可能になるMroongaに、mecab-ipadic-NEologdの機能を使ってインストールが可能になる編集を加えました。

I have to be able to install the mecab-ipadic-NEologd to Mroonga.
Mroonga is a storage engine for MySQL.
It provides fast fulltext search feature to all MySQL users.

Mroonga: http://mroonga.org/ja/

### CODE REVIEW

**Comment by neologd** [comment]
Thank you for your commit.
However, I couldn't understand the merit of your commit.
- I can't interpret the meaning of your commit message. 
  - You have said 'I changed the Mroonga'.
  - You should express an intention of your commit.
- I don't need .gitignore for JetBrains.
  - Why we add this file?
- Why we should add processes to check the existence of groonga-tokenizer-mecabuse package ?
  - Are there some critical problems with the code of current master branch ?
  - You should explain an unfavourable case which will occur by installing the mecab package.

Could you please answer for above comments ?
I'm sorry but I will close this request after 7 days if you don't add any comments.

**Comment by WhiteRaven777** [comment]
> I don't need .gitignore for JetBrains.
> Why we add this file?

This file is not required .
You do not need to merge .
I was a confusing thing , I'm sorry .

> Why we should add processes to check the existence of groonga-tokenizer-mecabuse package ?
> You should explain an unfavourable case which will occur by installing the mecab package.

I was intended to avoid conflicts of package.
I thought that it is better to avoid the installation of the package that does not use on the server's design .
If we use the mecab as tokenizer in Mroonga, it is required 'groonga-tokenizer-mecab'.
'groonga-tokenizer-mecab' is to contain the program to be used by the 'mecab-ipadic-NEologd'.
I believe it is better to use the already certain programs .
I hope that you will consider this proposal .

Thank you.

**Comment by neologd** [comment]
> This file is not required .

I totally agree.

> I hope that you will consider this proposal .

I checked an inside of groonga-tokenizer-mecab-6.0.3-1.*.rpm file with cpio command to consider your PR.
- http://packages.groonga.org/centos/

> If we use the mecab as tokenizer in Mroonga, it is required 'groonga-tokenizer-mecab'.
> 'groonga-tokenizer-mecab' is to contain the program to be used by the 'mecab-ipadic-NEologd'.

There seems to be a misunderstanding.
Could you please check the inside of groonga-tokenizer-mecab-6.0.3-1.*.rpm file ?

This RPM package has only mecab.so (/usr/lib64/groonga/plugins/tokenizers/mecab.so).
And this mecab.so file requires a libmecab.so.2 which is provided by a mecab package.

Therefore the groonga-tokenizer-mecab package depends on the mecab package.
The mecab package provides not only this libmecab.so.2 file but also a mecab-dict-index file.

> I thought that it is better to avoid the installation of the package that does not use on the server's design .

When you install the groonga-tokenizer-mecab package for the first time, the mecab package and a mecab-ipadic package are installed at the same time.
Because the groonga-tokenizer-mecab package depends on the mecab package.

Therefore, it isn't necessary to add processes to check the existence of groonga-tokenizer-mecab package.

Could you please answer if there are any errors in my comment ?
I'm sorry but I will close this request after 7 days if you don't add any comments.

**Comment by WhiteRaven777** [comment]
I was validated in Ubuntu 14.04 LTS on the AWS .

First , launch the instance .
Next, install the Mroonga according to the instructions below .
[mroonga.org - Mroonga v6.03 documentation » 2. Install » 2.4. Ubuntu](http://mroonga.org/docs/install/ubuntu.html)

---

Enable the universe repository and the security update repository to install Mroonga:

```
% sudo apt-get install -y -V software-properties-common lsb-release
% sudo add-apt-repository -y universe
% sudo add-apt-repository "deb http://security.ubuntu.com/ubuntu $(lsb_release --short --codename)-security main restricted"
```

Add the `ppa:groonga/ppa` PPA to your system:

```
% sudo add-apt-repository -y ppa:groonga/ppa
% sudo apt-get update
```

Install:
`% sudo apt-get install -y -V mysql-server-mroonga`

Install groonga-tokenizer-mecab package:
`% sudo apt-get install -y -V groonga-tokenizer-mecab`

---

I run the following command that is included in the `bin/install-mecab-ipadic-neologd`.

```
$ which mecab
$ which mecab-config
```

I could not be obtained even run a result of either of the command .
`groonga-tokenizer-mecab` does not install the `mecab` command and `mecab-config` command .
So , we can not confirm the presence of `mecab` command and `mecab-config` command in `which` command .

---

I've tried as well , even CentOS7.0.
First , launch the instance .
Next, install the Mroonga according to the instructions below .
[mroonga.org - Mroonga v6.03 documentation » 2. Install » 2.5. CentOS » 2.5.7. CentOS 7 (with the official MariaDB package)](http://mroonga.org/docs/install/centos.html#centos-7-with-the-official-mariadb-package)

Install:

```
% sudo yum install -y http://packages.groonga.org/centos/groonga-release-1.1.0-1.noarch.rpm
% sudo yum makecache
% sudo yum install -y mariadb-server
% sudo systemctl start mariadb
% sudo yum install -y mariadb-mroonga
(% sudo mysqladmin -u root password 'new-password')
```

Install groonga-tokenizer-mecab package:
`% sudo yum install -y groonga-tokenizer-mecab`

I run the following command that is included in the `bin/install-mecab-ipadic-neologd`.

```
$ which mecab
/usr/bin/mecab
$ which mecab-config
/usr/bin/which: no mecab-config in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
```

I got the results of the above command .
When I install the groonga-tokenizer-mecab to CentOS, we recognize that even `mecab` command and `mecab-config` command is installed .

---

However , is not the case in Ubuntu.
So, I hope that you will consider this proposal .

Thank you.

**Comment by WhiteRaven777** [comment]
@neologd 
How have things been after that?

**Comment by neologd** [comment]
Thank you for your work to get the result of technical verification.
And I'm sorry for the long delay in my reply.

I considered a management policy of this project.
And I realize what you can execute the groonga-tokenizer-mecab command for your purpose that relies on your environment.

Today, there are three points I have to tell you.

**Comment by neologd** [comment]
First, I decide temporary not to manage a code to improve user-friendliness for individual middleware user on this repository.

I focus our development resource on improvement of our dictionary resource in order to achieving our mid-term goal.
Of course, I can accept P-R to solve an “general" unfavourable case which has occur on Ubuntu Linux.

Other than Mroonga, there are a lot of middlewares which might be using mecab-ipadic-NEologd.
Should I manage the codes for many middlewares in preference to improving dictionary data ?

I think, I could support you when you provide a package which depends on mecab-ipadic-NEologd for many Mroonga users.

**Comment by neologd** [comment]
Next, if you are working on Ubuntu Linux, I recommend to install the mecab package.

As it’s written in Readme.md, the installing processes of mecab-ipadic-NEologd depends the mecab command.

The mecab command is using on libexec/test-mecab-ipadic-neologd.sh (see line 62 & 63).

If you don’t install mecab command, you can’t check the quality of the result of mecab-ipadic-NEologd.
I can't think that all of the Mroonga users don't need this process.

**Comment by neologd** [comment]
At last, if you are working on Ubuntu Linux, I strongly recommend to install the libmecab-dev package.

The installing processes of mecab-ipadic-NEologd depends the mecab-config command too.
The libmecab-dev package of Ubuntu Linux will install the mecab-config command to /usr/bin/.

You have use the find command to search the path to mecab-dict-index command under the root.

https://github.com/neologd/mecab-ipadic-neologd/pull/17/commits/d00f1d70e7cbc7d6a7a36d9f48853cf11aacb17e#diff-4f7c9a61cc23bcbe8ace408397680a4aR266

But, it doesn't seem to be able to work well.

In this case, the find command will scan the whole data storage area under the root.
Therefore, it’s impossible to estimate the execution time of this process.
In example, it took more than 5 minutes on my machine.

If you use the mecab-config command, you can find the path to mecab-dict-index command in a moment.

**Comment by neologd** [comment]
Thank you very much for your P-R which become a reason for considering a management policy of this project ✨.

Could you please answer if there are any errors in my comment ?

I'm sorry but I will close this request after 10 days if you don't add any comments.

**Comment by WhiteRaven777** [comment]
I understand the management policy of this project.
And , I will accept the policy.

I think that there is no error in your policy.

I like to build a new project to install this project in Mroonga, do you forgive me ?

Thank you.

**Comment by neologd** [comment]
Thank you for your reply.

> I like to build a new project to install this project in Mroonga, do you forgive me ?

Yes !! 😊
There are already many projects which are using mecab-ipadic-NEologd.

e.g.
- https://github.com/kazuhira-r/kuromoji-with-mecab-neologd-buildscript
- https://github.com/codelibs/elasticsearch-analysis-kuromoji-neologd
- https://github.com/mocobeta/lucene-solr/tree/kuromoji-neologd_5_4_0

If possible, l'd like you to use "./bin/install-mecab-ipadic-neologd -n ..." when you will update the seed data of mecab-ipadic-NEologd on your project.

Thank you very much.
I close this request.

**Pull request closed without merging**
